# ==============================================================================
# File: 01-postgres-secret.yml
# Purpose: Securely stores sensitive credentials like passwords instead of hardcoding them.
# Connection: This Secret is mounted/consumed by '04-postgres-deployment.yml' 
#             and '07-microservice-3.yml' so they can securely access the Database.
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  # The values MUST BE base64 encoded strings in Secret files
  # "postgres" = cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # "microservice3_db" = bWljcm9zZXJ2aWNlM19kYg==
  POSTGRES_DB: bWljcm9zZXJ2aWNlM19kYg==
